import type { MetadataRoute } from "next";

/** Icons generated by src/app/icon.tsx, served at /icon/{id}. The manifest lists the same set. */
export const APP_ICONS = [
  { id: "192", size: 192, purpose: "any" },
  { id: "512", size: 512, purpose: "any" },
  { id: "maskable", size: 512, purpose: "maskable" },
] as const;

export type AppIcon = (typeof APP_ICONS)[number];

/** Background of the installed app's splash screen and title bar (matches light mode). */
const APP_BACKGROUND = "#ffffff";

/** Web app manifest for the physio workspace. Patient links get their own (spec 10). */
export function buildManifest({
  locale,
  name,
  description,
}: {
  locale: string;
  name: string;
  description: string;
}): MetadataRoute.Manifest {
  return {
    id: "/",
    name,
    short_name: name,
    description,
    lang: locale,
    start_url: "/dashboard",
    scope: "/",
    display: "standalone",
    background_color: APP_BACKGROUND,
    theme_color: APP_BACKGROUND,
    icons: APP_ICONS.map((icon) => ({
      src: `/icon/${icon.id}`,
      sizes: `${icon.size}x${icon.size}`,
      type: "image/png",
      purpose: icon.purpose,
    })),
  };
}

/** Versioned so every deploy installs a new worker and drops the previous caches. */
export function serviceWorkerUrl(buildId: string): string {
  return `/sw.js?v=${encodeURIComponent(buildId)}`;
}
